"""empty message

Revision ID: cd14e9bd7cb5
Revises: 71dced2d6a91
Create Date: 2020-04-17 13:17:00.389672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd14e9bd7cb5'
down_revision = '71dced2d6a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_chat', table_name='chat')
    op.create_index(op.f('ix_chat_chat'), 'chat', ['chat'], unique=False)
    op.drop_index('ix_chat_user1', table_name='chat')
    op.create_index(op.f('ix_chat_user1'), 'chat', ['user1'], unique=False)
    op.drop_index('ix_chat_user2', table_name='chat')
    op.create_index(op.f('ix_chat_user2'), 'chat', ['user2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_user2'), table_name='chat')
    op.create_index('ix_chat_user2', 'chat', ['user2'], unique=1)
    op.drop_index(op.f('ix_chat_user1'), table_name='chat')
    op.create_index('ix_chat_user1', 'chat', ['user1'], unique=1)
    op.drop_index(op.f('ix_chat_chat'), table_name='chat')
    op.create_index('ix_chat_chat', 'chat', ['chat'], unique=1)
    # ### end Alembic commands ###
